### ISSUE TITLE
初期化の方法について

### ISSUE THREAD

**Issue by k2w4t4h** [link-u/cavif#1]
このコマンドを打ったところ
cavif -i /mnt/c/linux_home/avif-test/png/1.png -o /mnt/c/linux_home/avif-test/avif/1-000.avif --crf 55

[2020/01/26 21:16:44 FATAL] failed to encode a frame: Image size must match encoder init configuration size

こう怒られてしまうのですが、どうやって初期化すればよろしいでしょうか？

**Comment by ledyba-z** [comment]
縦幅と横幅が奇数の時に起こる不具合でした。直します。

**Comment by ledyba-z** [comment]
https://github.com/link-u/cavif/releases/tag/v0.1.0-20200127

で直しました。（一応、奇数と偶数の全４通りの組み合わせは試しました）
