### ISSUE TITLE
Bug? Different output filesize if --cpu-used 1 and --cpu-used 0

### ISSUE THREAD

**Issue by necros2k7** [link-u/cavif#112]
cavif -i 1.png -o 1.avif --lossless --threads 4 --cpu-used 1 and 
cavif -i 1.png -o 1.avif --lossless --threads 4 --cpu-used 0 give different filesize

sample:

![1](https://user-images.githubusercontent.com/16452453/111864090-81881180-89bb-11eb-97f0-12b848b5582b.PNG)

**Comment by ledyba-z** [comment]
It's expected behaviour:

```
   * Changes in this value influences the complexity of algorithms used in
   * encoding process, values greater than 0 will increase encoder speed at
   * the expense of quality.
   *
   * Valid range: 0..9. 0 runs the slowest, and 9 runs the fastest;
   * quality improves as speed decreases (since more compression
   * possibilities are explored).
```

In a nutshell, if you change the cpu-used parameter, libaom uses different algorithms and makes different results.
