### ISSUE TITLE
Support rav1e

### ISSUE THREAD

**Issue by Seirdy** [link-u/cavif#15]
Really like this CLI encoder, but libaom is a bit slow. Using [rav1e](https://github.com/xiph/rav1e) if available could significantly speed up encoding.

**Comment by megapro17** [comment]
it is not so much faster, and lacks a lot of useful features

**Comment by ledyba-z** [comment]
@Seirdy I'm so really to be late reply.

The aim of cavif is encoding images to AVIF in good quality with small size, rather than encoding speed.

If rav1e can encode images with better quality than libaom, I would like to support rav1e.

Do you know about it?

**Comment by megapro17** [comment]
> if rav1e can encode images with better quality than libaom

it can't

**Comment by Seirdy** [comment]
@ledyba-z outside of edge cases, I don't believe it can.

**Comment by ledyba-z** [comment]
@Seirdy I see, thanks.

So can I close this issue? If you found cases that rav1e can achieve better quality than libaom, don't hesitate to reopen this issue! It's welcome.

To tell you the truth, if I support rav1e in cavif, maybe some options in cavif can't be used, and I have to investigate about it periodically. It is too burden to me....

And also, please consider using `--cpu-used 8` option in cavif. If you use this option, libaom tries to encode images faster (in exchange for qualities of images).

**Comment by megapro17** [comment]
`--cpu-used 8` not worth using, it is worse than hevc with the same speed, the most optimal value is 3

**Comment by ledyba-z** [comment]
libaom currently supports `--cpu-used 9`.

**Comment by ledyba-z** [comment]
In libaom v3.2.0,  libaom introduced an API that allows external partition decisions. We would like to support those libaom's specific APIs instead of supporting rav1e.
