### ISSUE TITLE
Debian builds are broken

### ISSUE THREAD

**Issue by rootwork** [link-u/cavif#164]
See e.g. https://github.com/link-u/cavif/actions/runs/1351842568

The Debian bundle at https://github.com/link-u/cavif/releases/tag/v0.1.0-20200331 can still be downloaded and installed, but when you try to use `cavif`, the generated AVIF file has errors and can't be opened.

**Comment by ledyba-z** [comment]
Thanks for reporting.

We has been working to resolve build issues on mac, windows and debian packages.
And it's done now!

Commits: https://github.com/link-u/cavif/compare/805477cc158890012de82fb64998e212bb135ca5...eb78fc71b5105ccfd6ac9aa3663c47a528f0be37
