### ISSUE TITLE
RGBからYUVに変換するときの係数を選択できるようにしてほしい

### ISSUE THREAD

**Issue by f11894** [link-u/cavif#2]
現在は多分BT.2020で変換していると思うのですがBT.601やBT.709でも変換できるようにしてほしいです

**Comment by ledyba-z** [comment]
遅れました。

さっきリリースしたバージョン（`v0.1.0-20200317-1`）で

- Rec. ITU-R BT.709-6 (sRGB/sYCC)
- USFCC: United States Federal Communications Commission (2003) Title 47 Code of Federal Regulations 73.682 (a) (20)
- Rec. ITU-R BT.601-7 625
- Rec. ITU-R BT.1700-0 NTSC
- SMPTE 240M (1999)
- Rec. ITU-R BT.2020-2 (non-constant luminance)

に対応しました。 
https://github.com/link-u/cavif/releases/tag/v0.1.0-20200317-1

davifでも同じように対応してます：
https://github.com/link-u/davif/releases/tag/v0.1.0-20200317

指定するためのフラグに関してはこちら：
https://github.com/link-u/cavif/blob/master/doc/ja_JP/usage.md#matrix-coefficients

**Comment by f11894** [comment]
ありがとうございます。
これで手持ちの画像をバカスカ変換出来ます。
