### ISSUE TITLE
Misfunction When Converting from Png Files

### ISSUE THREAD

**Issue by GrandArth** [link-u/cavif#27]
![2](https://user-images.githubusercontent.com/30680793/86462568-5fcbf900-bd5e-11ea-9e46-9edf4294e1ea.png)
This is my original png file.

[1.zip](https://github.com/link-u/cavif/files/4869292/1.zip)
![3](https://user-images.githubusercontent.com/30680793/86462734-b0dbed00-bd5e-11ea-8a83-561506f5adae.png)
This is what i got with
```
cavif -i 2.png --cpu-used 0 --enable-cdef --crf 10 --threads 4 --rate-control q --enable-full-color-range -o 1.avif
```
This is the output text i got.
```
[2020/07/03 18:54:37 INFO ] cavif
[2020/07/03 18:54:37 INFO ] libaom ver: 1.0.0-errata1-avif-414-g0cfdca944
[2020/07/03 18:54:38 INFO ] Encoding: 2.png -> 1.avif
[2020/07/03 18:54:56 INFO ]  Encoded: 2.png -> 1.avif in 17.99 [sec]
```
Any ideas?
Cavif is probably the most balanced CLI tool, i really hope to get this settled.

**Comment by f11894** [comment]
It's a issue of chroma subsampling.
Try adding the following arguments.
```
--profile 1 --pix-fmt yuv444 
```

**Comment by GrandArth** [comment]
This solved my problem, thx for replying.
