### ISSUE TITLE
--enable-full-color-rangeを有効にしたときはYUVの範囲をフルレンジで変換してほしい

### ISSUE THREAD

**Issue by f11894** [link-u/cavif#3]
現状ではリミテッドレンジで変換されているようでAVIF用Susieプラグインの[ifavif](https://github.com/uyjulian/ifavif)で画像を読み込むとYC伸長されていないコントラストの低い絵になってしまいました
また[libavif](https://github.com/AOMediaCodec/libavif)でavifをy4mに変換してAviUtlに読み込ませた際のヒストグラムの範囲がリミテッドレンジになっていることも確認しました

**Comment by ledyba-z** [comment]
[H.273](https://www.itu.int/rec/T-REC-H.273/en)という規格でフルレンジの時の変換式を定めているのを発見したので、実装してみました（--enable-full-range-colorを指定すると自動でフルレンジで変換します）：

libavif-container: https://github.com/link-u/libavif-container/commit/3532b3332c9799fb6956610eae29d966997da715
davif: https://github.com/link-u/davif/commit/4461ba59fd304e1b1df530996f787616763267ca
cavif: https://github.com/link-u/cavif/commit/635b0ab0679781d0222280d46ecd322b88ae69f0

mastarブランチにはもうpushしてあって、リリースはもうちょっとテストしたらする予定です。

**Comment by ledyba-z** [comment]
https://github.com/link-u/cavif/releases/tag/v0.1.0-20200208
多少テストをした結果、問題なさそうなのでリリースしました。

**Comment by f11894** [comment]
対応していただきありがとうございます

**Comment by ledyba-z** [comment]
いえいえ！
また何かあったらお願いします。

**Comment by ledyba-z** [comment]
すいません、エンコーダにはFull Color Rangeを指定してたんですが、渡す画像にFull Color Rangeを指定しわすれてて実際にはまだ暗い画像になってました（CIを回してて気づいた）

これで修正して： https://github.com/link-u/cavif/commit/f9c7bc4631080cd7d2c8cf95517b91929e3896b3
リリースはこちらです：https://github.com/link-u/cavif/releases/tag/v0.1.0-20200209-1
