### ISSUE TITLE
We moved to avif-community! / avif-communityでの開発に移行しました。

### ISSUE THREAD

**Issue by ledyba-z** [link-u/cavif#300]
Hi, I'm a original developer of cavif.
I leaved link-u, and the development process has been moved to [avif-community](https://github.com/avif-community)!

Stay tuned!

@Kotaro-Shibata 迷う人がいるからこういう内容をREADME.mdに書いておいてもらえると助かる

**Comment by Kotaro-Shibata** [comment]
@ledyba-z I wrote it. You don't get wrong. This is a volunteer work.

Link-U is not related to the activities of the avif-community at all. We have no responsibility of the confusing community name. it's not related to the official AVIF codec organization.

This repository is removed after 2023-01-31 to resolve this confusing situation.

免責事項です。ややこしいコミュニティだとそういうトラブルが起こることがあるので、念の為。
