### ISSUE TITLE
AOMにfull-still-picture-headerのPRを投げる

### ISSUE THREAD

**Issue by k2w4t4h** [link-u/cavif#5]

**Comment by ledyba-z** [comment]
ドキュメントの間違いでした：

```
  /*!\brief Codec control function to force video mode
   *
   *                          0 = do not force video mode
   *                          1 = force video mode even for a single frame
   *
   *  By default, the encoder does not force video and allows still picture.
   *
   */
  AV1E_SET_FORCE_VIDEO_MODE = 60,
```

https://aomedia.googlesource.com/aom/+/7b5d6d82aaf29f33e369c1914b9e3667c5ddeead/aom/aomcx.h#596

このデフォルトでは無効ということになってる、force video modeというのが1になってるとfull-still-picture-headerが出なくなるんですが（videoだから）、実際の値を確認すると：

```
  1,                                         // force_video_mode
```
https://aomedia.googlesource.com/aom/+/7b5d6d82aaf29f33e369c1914b9e3667c5ddeead/av1/av1_cx_iface.c#183

１じゃねーか。

とりあえずcavifでは0でデフォルト値を上書きしつつ、libaomに報告する作戦で行きます。

**Comment by ledyba-z** [comment]
https://github.com/link-u/cavif/commit/645b9e60979748f790d68d4b7d32768c95ac6af2

で直しました。

あとこっちのドキュメントも嘘をついてて、`--full-still-picture-header` を指定**する**と動画用の長いヘッダが出力されるのが正解です。

修正コミット：https://github.com/link-u/cavif/commit/229cd504ebb5605dfb3e61a70f7ac24397a28412

なのでこのオプションは基本的には指定しなくてよいと思うんですが、ブラウザで<video/>要素に食わせた時に、このフラグを指定して動画用の長いヘッダを出力させないとブラウザがデコードしてくれないかもしれません（実験しないとわからん）。

**Comment by ledyba-z** [comment]
どっちが正しいのかはAOMアライアンスのお気持ち次第なのでIssueを立てた：

2577 - the default value of "forced video mode" is not 0, as descrived in aomcx.h. - aomedia - The open and royalty-free codec for next-generation ultra high definition media - Monorail
https://bugs.chromium.org/p/aomedia/issues/detail?id=2577

**Comment by ledyba-z** [comment]
超速で対応してくれた：

Correct a default value (I4c5e3bcf) · Gerrit Code Review
https://aomedia-review.googlesource.com/c/aom/+/104001

わたしもLGTMを出して、さらに他の人のレビュー待ち。

v1.1.0がもうすぐ出るらしい。

**Comment by ledyba-z** [comment]
https://bugs.chromium.org/p/aomedia/issues/detail?id=2577#c6

超速でFixedになった。doneで。
