### ISSUE TITLE
How to enable Full Suport Alpha?

### ISSUE THREAD

**Issue by ghost** [link-u/cavif#63]
I have the alpha channel removed!
How not to clean it?
Give me config!

**Comment by ledyba-z** [comment]
You have to separately encode: RGB image and alpha image.

Here is an example (copied from README):
```
cavif -i <input.png> -o <output-alpha.avif> --encode-target alpha --monochrome
cavif -i <input.png> -o <output.avif> --encode-target image --attach-alpha <output-alpha.avif>
```

You can encode alpha image losslessly, while RGB image lossy, or vice versa.
