### ISSUE TITLE
MSYS2でのビルドのサポート

### ISSUE THREAD

**Issue by f11894** [link-u/cavif#9]
Windows用のバイナリを作成したいのですがMSYS2ではビルドに失敗してしまいます
AppVeyorでビルドしていてビルドログは以下にあります
https://ci.appveyor.com/project/f11894/cavif

appveyor.ymlの内容はこんな感じになります
https://pastebin.com/q4nrHYs4

**Comment by ledyba-z** [comment]
ありがとうございます。
Windows版MinGWにないuintという謎の型を使っていたのが原因でした。

https://github.com/link-u/cavif/commit/7b44af1c8f1d854969e5439465987861968d1a11
で直して、appveyor.ymlを追加したら出来るようになりました：
https://ci.appveyor.com/project/ledyba-z/cavif/build/artifacts

（今後もぐるぐるCI回してReleaseする時にdebian packageと一緒にリリースして見る予定です）

**Comment by f11894** [comment]
対応いただきありがとうございます。
公式にappveyor.ymlを追加してもらえると非常に助かります。

それとMSYS2でのビルドなのですがlibwinpthreadがgit-7.0.0.5535以下だとデッドロックが発生する問題があるようです。
https://github.com/msys2/MINGW-packages/issues/5610

上で例に挙げたappveyor.ymlだとその辺の配慮が抜け落ちていてgit 7.0.0.5480が使われてしまっているみたいです。
Build worker imageにVisual Studio 2019を使うとgit 8.0.0.5574が使われるようなので修正お願いします。
```
version: 1.0.{build}
image: Visual Studio 2019
build_script:
```

**Comment by ledyba-z** [comment]
@f11894 あっ、連絡が遅れてすいません。
というわけで、次からはcavif/davifがappveyorでビルドされてリリースに一緒に配布されるようになります（あとpthreadの問題も修正しました）。
ご協力ありがとうございます。
